version: '3'

tasks:

    default: task -l

    preview:
        desc: preview the websites
        cmds:
        - hugo server

    debug:
        desc: debug the websites
        cmds:
        - hugo server --ignoreCache  --debug --disableFastRender