name: test

on:
  push:
    branches:
      - main

#permissions:
#  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix-build
    - run: nix-shell --run "echo OK"
    - name: Install Hugo
      run: |
        nix-env -iA nixpkgs.hugo

    - name: Build Hugo site
      run: |
        hugo
    
    #- name: Deploy to ASF
    #  run: |
    #    cp -r public/* $GITHUB_WORKSPACE/public/